macro(use_c99)
    if (CMAKE_VERSION LESS "3.1")
        if (CMAKE_C_COMPILER_ID STREQUAL "GNU")
            set (CMAKE_CFLAGS "--std=gnu99 ${CMAKE_C_FLAGS}")
        endif()
    else ()
        set(CMAKE_C_STANDARD 99)
    endif()
endmacro(use_c99)
